spring:
  application:
    name: springboot-jpa
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot?createDatabaseIfNotExists=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create